"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23 13:58:53.532289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('name', name=op.f('uq_vendors_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_vendors_slug'))
    )
    op.create_table('alert_channels',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target_enc', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_channels_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_channels'))
    )
    op.create_index(op.f('ix_alert_channels_tenant_id'), 'alert_channels', ['tenant_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('channel_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('throttle_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_event_type'), 'alert_rules', ['event_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('pk_audit_events')),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_ts', 'audit_events', ['actor_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_events_target', 'audit_events', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('command_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('device_address', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('source_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.String(length=32), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=True),
    sa.Column('record_type', sa.String(length=8), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('priv_lvl', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_command_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('pk_command_logs')),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_index('ix_command_logs_device_ts', 'command_logs', ['device_address', 'timestamp'], unique=False)
    op.create_index(op.f('ix_command_logs_session_id'), 'command_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_command_logs_tenant_id'), 'command_logs', ['tenant_id'], unique=False)
    op.create_index('ix_command_logs_user_ts', 'command_logs', ['username', 'timestamp'], unique=False)
    op.create_table('compliance_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('devices_checked', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_runs'))
    )
    op.create_index(op.f('ix_compliance_runs_started_at'), 'compliance_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_compliance_runs_tenant_id'), 'compliance_runs', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('ssh_key_enc', sa.Text(), nullable=True),
    sa.Column('enable_secret_enc', sa.Text(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_credentials_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_credentials_tenant_id_name'))
    )
    op.create_index(op.f('ix_credentials_tenant_id'), 'credentials', ['tenant_id'], unique=False)
    op.create_table('device_groups',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('dynamic_filter', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['device_groups.id'], name=op.f('fk_device_groups_parent_id_device_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_groups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_groups')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_device_groups_tenant_id_name'))
    )
    op.create_index(op.f('ix_device_groups_tenant_id'), 'device_groups', ['tenant_id'], unique=False)
    op.create_table('device_models',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_device_models_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_models')),
    sa.UniqueConstraint('vendor_id', 'name', name=op.f('uq_device_models_vendor_id_name'))
    )
    op.create_table('external_objects',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_external_objects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_objects')),
    sa.UniqueConstraint('tenant_id', 'source', 'object_type', 'external_id', name=op.f('uq_external_objects_tenant_id_source_object_type_external_id'))
    )
    op.create_index(op.f('ix_external_objects_tenant_id'), 'external_objects', ['tenant_id'], unique=False)
    op.create_index('ix_external_objects_type', 'external_objects', ['tenant_id', 'object_type'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_dn', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_groups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_groups_tenant_id_name'))
    )
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=True),
    sa.Column('last_sync_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_integrations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('tenant_id', 'kind', 'name', name=op.f('uq_integrations_tenant_id_kind_name'))
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('ixp_members',
    sa.Column('asn', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('peering_policy', sa.String(length=32), nullable=True),
    sa.Column('member_type', sa.String(length=32), nullable=True),
    sa.Column('contacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('connections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('traffic', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ixp_members_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ixp_members')),
    sa.UniqueConstraint('tenant_id', 'asn', name=op.f('uq_ixp_members_tenant_id_asn'))
    )
    op.create_index(op.f('ix_ixp_members_asn'), 'ixp_members', ['asn'], unique=False)
    op.create_index(op.f('ix_ixp_members_tenant_id'), 'ixp_members', ['tenant_id'], unique=False)
    op.create_table('platforms',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('scrapli_platform', sa.String(length=64), nullable=True),
    sa.Column('netmiko_device_type', sa.String(length=64), nullable=True),
    sa.Column('backup_commands', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tacacs_service', sa.String(length=32), nullable=False),
    sa.Column('supports_tacacs', sa.Boolean(), nullable=False),
    sa.Column('supports_config_replace', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_platforms_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('slug', name=op.f('uq_platforms_slug'))
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_regions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('tenant_id', 'slug', name=op.f('uq_regions_tenant_id_slug'))
    )
    op.create_index(op.f('ix_regions_tenant_id'), 'regions', ['tenant_id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('fmt', sa.String(length=8), nullable=False),
    sa.Column('recipients', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_report_schedules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedules'))
    )
    op.create_index(op.f('ix_report_schedules_tenant_id'), 'report_schedules', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_roles_tenant_id_name'))
    )
    op.create_table('route_server_clients',
    sa.Column('route_server', sa.String(length=64), nullable=False),
    sa.Column('protocol_name', sa.String(length=128), nullable=False),
    sa.Column('asn', sa.BigInteger(), nullable=False),
    sa.Column('neighbor_address', sa.String(length=64), nullable=False),
    sa.Column('address_family', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('prefixes_accepted', sa.Integer(), nullable=False),
    sa.Column('prefixes_filtered', sa.Integer(), nullable=False),
    sa.Column('prefixes_exported', sa.Integer(), nullable=False),
    sa.Column('irr_filtered', sa.Integer(), nullable=False),
    sa.Column('rpki_invalid', sa.Integer(), nullable=False),
    sa.Column('rpki_status', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('irr_status', sa.String(length=32), nullable=True),
    sa.Column('since', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_route_server_clients_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_server_clients')),
    sa.UniqueConstraint('tenant_id', 'route_server', 'protocol_name', name=op.f('uq_route_server_clients_tenant_id_route_server_protocol_name'))
    )
    op.create_index(op.f('ix_route_server_clients_asn'), 'route_server_clients', ['asn'], unique=False)
    op.create_index(op.f('ix_route_server_clients_tenant_id'), 'route_server_clients', ['tenant_id'], unique=False)
    op.create_table('tacacs_auth_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('device_address', sa.String(length=64), nullable=False),
    sa.Column('source_address', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_auth_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('pk_tacacs_auth_events')),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_index(op.f('ix_tacacs_auth_events_tenant_id'), 'tacacs_auth_events', ['tenant_id'], unique=False)
    op.create_index('ix_tacacs_auth_events_ts', 'tacacs_auth_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tacacs_auth_events_username'), 'tacacs_auth_events', ['username'], unique=False)
    op.create_table('tacacs_servers',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ldap_backend', sa.Boolean(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_token_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_servers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_servers')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_tacacs_servers_tenant_id_name'))
    )
    op.create_index(op.f('ix_tacacs_servers_tenant_id'), 'tacacs_servers', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sa.Text(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'username', name=op.f('uq_users_tenant_id_username'))
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('api_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('pre_backup_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('post_backup_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('external_ticket', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_change_requests_approved_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_change_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_change_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests')),
    sa.UniqueConstraint('tenant_id', 'number', name=op.f('uq_change_requests_tenant_id_number'))
    )
    op.create_index(op.f('ix_change_requests_number'), 'change_requests', ['number'], unique=False)
    op.create_index(op.f('ix_change_requests_state'), 'change_requests', ['state'], unique=False)
    op.create_index(op.f('ix_change_requests_tenant_id'), 'change_requests', ['tenant_id'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('block_start', sa.String(length=512), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], name=op.f('fk_compliance_rules_device_group_id_device_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_rules'))
    )
    op.create_index(op.f('ix_compliance_rules_tenant_id'), 'compliance_rules', ['tenant_id'], unique=False)
    op.create_table('login_history',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_login_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_history'))
    )
    op.create_index(op.f('ix_login_history_tenant_id'), 'login_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_login_history_timestamp'), 'login_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_bindings',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_role_bindings_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_bindings_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_role_bindings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_bindings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_bindings'))
    )
    op.create_index(op.f('ix_role_bindings_tenant_id'), 'role_bindings', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sites',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('netbox_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_sites_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sites_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('tenant_id', 'slug', name=op.f('uq_sites_tenant_id_slug'))
    )
    op.create_index(op.f('ix_sites_netbox_id'), 'sites', ['netbox_id'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('tacacs_config_revisions',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_tacacs_config_revisions_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['tacacs_servers.id'], name=op.f('fk_tacacs_config_revisions_server_id_tacacs_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_config_revisions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_config_revisions'))
    )
    op.create_index(op.f('ix_tacacs_config_revisions_server_id'), 'tacacs_config_revisions', ['server_id'], unique=False)
    op.create_index(op.f('ix_tacacs_config_revisions_tenant_id'), 'tacacs_config_revisions', ['tenant_id'], unique=False)
    op.create_table('tacacs_policies',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=True),
    sa.Column('privilege_level', sa.Integer(), nullable=False),
    sa.Column('junos_class', sa.String(length=64), nullable=True),
    sa.Column('fortigate_profile', sa.String(length=64), nullable=True),
    sa.Column('arista_role', sa.String(length=64), nullable=True),
    sa.Column('extra_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('default_action', sa.String(length=8), nullable=False),
    sa.Column('time_window', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], name=op.f('fk_tacacs_policies_device_group_id_device_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_tacacs_policies_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_policies')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_tacacs_policies_tenant_id_name'))
    )
    op.create_index(op.f('ix_tacacs_policies_tenant_id'), 'tacacs_policies', ['tenant_id'], unique=False)
    op.create_table('tacacs_user_mappings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tacacs_username', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=16), nullable=False),
    sa.Column('password_crypt', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_user_mappings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tacacs_user_mappings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_user_mappings')),
    sa.UniqueConstraint('tenant_id', 'tacacs_username', name=op.f('uq_tacacs_user_mappings_tenant_id_tacacs_username'))
    )
    op.create_index(op.f('ix_tacacs_user_mappings_tenant_id'), 'tacacs_user_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tacacs_user_mappings_user_id'), 'tacacs_user_mappings', ['user_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_groups'))
    )
    op.create_table('change_request_comments',
    sa.Column('change_request_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('transition', sa.String(length=48), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_change_request_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_change_request_comments_change_request_id_change_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_change_request_comments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_request_comments'))
    )
    op.create_index(op.f('ix_change_request_comments_change_request_id'), 'change_request_comments', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_change_request_comments_tenant_id'), 'change_request_comments', ['tenant_id'], unique=False)
    op.create_table('racks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('u_height', sa.Integer(), nullable=False),
    sa.Column('netbox_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_racks_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_racks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racks'))
    )
    op.create_index(op.f('ix_racks_netbox_id'), 'racks', ['netbox_id'], unique=False)
    op.create_index(op.f('ix_racks_site_id'), 'racks', ['site_id'], unique=False)
    op.create_index(op.f('ix_racks_tenant_id'), 'racks', ['tenant_id'], unique=False)
    op.create_table('tacacs_command_policies',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_on_match', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['tacacs_policies.id'], name=op.f('fk_tacacs_command_policies_policy_id_tacacs_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_command_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_command_policies'))
    )
    op.create_index(op.f('ix_tacacs_command_policies_policy_id'), 'tacacs_command_policies', ['policy_id'], unique=False)
    op.create_index(op.f('ix_tacacs_command_policies_tenant_id'), 'tacacs_command_policies', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('management_ip', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('rack_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('platform_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('serial', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reachability', sa.String(length=16), nullable=False),
    sa.Column('backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('netbox_id', sa.Integer(), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backup_status', sa.String(length=16), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_devices_credential_id_credentials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['device_models.id'], name=op.f('fk_devices_model_id_device_models')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_devices_platform_id_platforms')),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('fk_devices_rack_id_racks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_devices_site_id_sites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_devices_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_devices_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('tenant_id', 'hostname', name=op.f('uq_devices_tenant_id_hostname'))
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_management_ip'), 'devices', ['management_ip'], unique=False)
    op.create_index(op.f('ix_devices_netbox_id'), 'devices', ['netbox_id'], unique=False)
    op.create_index(op.f('ix_devices_platform_id'), 'devices', ['platform_id'], unique=False)
    op.create_index(op.f('ix_devices_serial'), 'devices', ['serial'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('delivered', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alerts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_event_type'), 'alerts', ['event_type'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('config_backups',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_config_backups_change_request_id_change_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_config_backups_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_config_backups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_backups'))
    )
    op.create_index(op.f('ix_config_backups_collected_at'), 'config_backups', ['collected_at'], unique=False)
    op.create_index(op.f('ix_config_backups_commit_sha'), 'config_backups', ['commit_sha'], unique=False)
    op.create_index('ix_config_backups_device_time', 'config_backups', ['device_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_config_backups_tenant_id'), 'config_backups', ['tenant_id'], unique=False)
    op.create_table('device_compliance_scores',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_compliance_scores_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], name=op.f('fk_device_compliance_scores_run_id_compliance_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_compliance_scores_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_compliance_scores'))
    )
    op.create_index(op.f('ix_device_compliance_scores_device_id'), 'device_compliance_scores', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_compliance_scores_run_id'), 'device_compliance_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_device_compliance_scores_tenant_id'), 'device_compliance_scores', ['tenant_id'], unique=False)
    op.create_table('device_group_members',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], name=op.f('fk_device_group_members_device_group_id_device_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_group_members_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'device_group_id', name=op.f('pk_device_group_members'))
    )
    op.create_table('drift_events',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_drift_events_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_drift_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drift_events'))
    )
    op.create_index(op.f('ix_drift_events_detected_at'), 'drift_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_drift_events_device_id'), 'drift_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_drift_events_tenant_id'), 'drift_events', ['tenant_id'], unique=False)
    op.create_table('golden_configs',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('device_group_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ignore_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], name=op.f('fk_golden_configs_device_group_id_device_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_golden_configs_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_golden_configs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_configs'))
    )
    op.create_index(op.f('ix_golden_configs_tenant_id'), 'golden_configs', ['tenant_id'], unique=False)
    op.create_table('links',
    sa.Column('a_device_id', sa.Uuid(), nullable=False),
    sa.Column('a_interface', sa.String(length=64), nullable=False),
    sa.Column('b_device_id', sa.Uuid(), nullable=False),
    sa.Column('b_interface', sa.String(length=64), nullable=False),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['a_device_id'], ['devices.id'], name=op.f('fk_links_a_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_device_id'], ['devices.id'], name=op.f('fk_links_b_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links'))
    )
    op.create_index(op.f('ix_links_a_device_id'), 'links', ['a_device_id'], unique=False)
    op.create_index(op.f('ix_links_b_device_id'), 'links', ['b_device_id'], unique=False)
    op.create_index(op.f('ix_links_tenant_id'), 'links', ['tenant_id'], unique=False)
    op.create_table('session_recordings',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('device_address', sa.String(length=64), nullable=False),
    sa.Column('source_address', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('commands', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tacacs_session_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_session_recordings_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_session_recordings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_recordings'))
    )
    op.create_index(op.f('ix_session_recordings_device_id'), 'session_recordings', ['device_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_started_at'), 'session_recordings', ['started_at'], unique=False)
    op.create_index(op.f('ix_session_recordings_tenant_id'), 'session_recordings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_username'), 'session_recordings', ['username'], unique=False)
    op.create_table('tacacs_devices',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('key_enc', sa.Text(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('key_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], name=op.f('fk_tacacs_devices_device_group_id_device_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_tacacs_devices_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tacacs_devices_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tacacs_devices')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_tacacs_devices_tenant_id_name'))
    )
    op.create_index(op.f('ix_tacacs_devices_tenant_id'), 'tacacs_devices', ['tenant_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('backup_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], name=op.f('fk_compliance_results_backup_id_config_backups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_compliance_results_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], name=op.f('fk_compliance_results_rule_id_compliance_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], name=op.f('fk_compliance_results_run_id_compliance_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    op.create_index(op.f('ix_compliance_results_device_id'), 'compliance_results', ['device_id'], unique=False)
    op.create_index('ix_compliance_results_run_device', 'compliance_results', ['run_id', 'device_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_tenant_id'), 'compliance_results', ['tenant_id'], unique=False)
    op.create_table('config_index',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], name=op.f('fk_config_index_backup_id_config_backups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_config_index_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_config_index_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_index'))
    )
    op.create_index('ix_config_index_device', 'config_index', ['device_id'], unique=False)
    op.create_index('ix_config_index_kind_key', 'config_index', ['tenant_id', 'kind', 'key'], unique=False)
    op.create_index(op.f('ix_config_index_tenant_id'), 'config_index', ['tenant_id'], unique=False)
    op.create_table('config_restores',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('device_diff', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('pre_restore_backup_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], name=op.f('fk_config_restores_backup_id_config_backups')),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_config_restores_change_request_id_change_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_config_restores_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_config_restores_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_config_restores_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_restores'))
    )
    op.create_index(op.f('ix_config_restores_device_id'), 'config_restores', ['device_id'], unique=False)
    op.create_index(op.f('ix_config_restores_tenant_id'), 'config_restores', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_restores_tenant_id'), table_name='config_restores')
    op.drop_index(op.f('ix_config_restores_device_id'), table_name='config_restores')
    op.drop_table('config_restores')
    op.drop_index(op.f('ix_config_index_tenant_id'), table_name='config_index')
    op.drop_index('ix_config_index_kind_key', table_name='config_index')
    op.drop_index('ix_config_index_device', table_name='config_index')
    op.drop_table('config_index')
    op.drop_index(op.f('ix_compliance_results_tenant_id'), table_name='compliance_results')
    op.drop_index('ix_compliance_results_run_device', table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_device_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_tacacs_devices_tenant_id'), table_name='tacacs_devices')
    op.drop_table('tacacs_devices')
    op.drop_index(op.f('ix_session_recordings_username'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_tenant_id'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_started_at'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_device_id'), table_name='session_recordings')
    op.drop_table('session_recordings')
    op.drop_index(op.f('ix_links_tenant_id'), table_name='links')
    op.drop_index(op.f('ix_links_b_device_id'), table_name='links')
    op.drop_index(op.f('ix_links_a_device_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_golden_configs_tenant_id'), table_name='golden_configs')
    op.drop_table('golden_configs')
    op.drop_index(op.f('ix_drift_events_tenant_id'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_device_id'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_detected_at'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_table('device_group_members')
    op.drop_index(op.f('ix_device_compliance_scores_tenant_id'), table_name='device_compliance_scores')
    op.drop_index(op.f('ix_device_compliance_scores_run_id'), table_name='device_compliance_scores')
    op.drop_index(op.f('ix_device_compliance_scores_device_id'), table_name='device_compliance_scores')
    op.drop_table('device_compliance_scores')
    op.drop_index(op.f('ix_config_backups_tenant_id'), table_name='config_backups')
    op.drop_index('ix_config_backups_device_time', table_name='config_backups')
    op.drop_index(op.f('ix_config_backups_commit_sha'), table_name='config_backups')
    op.drop_index(op.f('ix_config_backups_collected_at'), table_name='config_backups')
    op.drop_table('config_backups')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_serial'), table_name='devices')
    op.drop_index(op.f('ix_devices_platform_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_netbox_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_management_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_tacacs_command_policies_tenant_id'), table_name='tacacs_command_policies')
    op.drop_index(op.f('ix_tacacs_command_policies_policy_id'), table_name='tacacs_command_policies')
    op.drop_table('tacacs_command_policies')
    op.drop_index(op.f('ix_racks_tenant_id'), table_name='racks')
    op.drop_index(op.f('ix_racks_site_id'), table_name='racks')
    op.drop_index(op.f('ix_racks_netbox_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_change_request_comments_tenant_id'), table_name='change_request_comments')
    op.drop_index(op.f('ix_change_request_comments_change_request_id'), table_name='change_request_comments')
    op.drop_table('change_request_comments')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_tacacs_user_mappings_user_id'), table_name='tacacs_user_mappings')
    op.drop_index(op.f('ix_tacacs_user_mappings_tenant_id'), table_name='tacacs_user_mappings')
    op.drop_table('tacacs_user_mappings')
    op.drop_index(op.f('ix_tacacs_policies_tenant_id'), table_name='tacacs_policies')
    op.drop_table('tacacs_policies')
    op.drop_index(op.f('ix_tacacs_config_revisions_tenant_id'), table_name='tacacs_config_revisions')
    op.drop_index(op.f('ix_tacacs_config_revisions_server_id'), table_name='tacacs_config_revisions')
    op.drop_table('tacacs_config_revisions')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_netbox_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_bindings_tenant_id'), table_name='role_bindings')
    op.drop_table('role_bindings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_timestamp'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_tenant_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_compliance_rules_tenant_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_index(op.f('ix_change_requests_tenant_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_state'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_number'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tacacs_servers_tenant_id'), table_name='tacacs_servers')
    op.drop_table('tacacs_servers')
    op.drop_index(op.f('ix_tacacs_auth_events_username'), table_name='tacacs_auth_events')
    op.drop_index('ix_tacacs_auth_events_ts', table_name='tacacs_auth_events')
    op.drop_index(op.f('ix_tacacs_auth_events_tenant_id'), table_name='tacacs_auth_events')
    op.drop_table('tacacs_auth_events')
    op.drop_index(op.f('ix_route_server_clients_tenant_id'), table_name='route_server_clients')
    op.drop_index(op.f('ix_route_server_clients_asn'), table_name='route_server_clients')
    op.drop_table('route_server_clients')
    op.drop_table('roles')
    op.drop_index(op.f('ix_report_schedules_tenant_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_regions_tenant_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_ixp_members_tenant_id'), table_name='ixp_members')
    op.drop_index(op.f('ix_ixp_members_asn'), table_name='ixp_members')
    op.drop_table('ixp_members')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_external_objects_type', table_name='external_objects')
    op.drop_index(op.f('ix_external_objects_tenant_id'), table_name='external_objects')
    op.drop_table('external_objects')
    op.drop_table('device_models')
    op.drop_index(op.f('ix_device_groups_tenant_id'), table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_credentials_tenant_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_compliance_runs_tenant_id'), table_name='compliance_runs')
    op.drop_index(op.f('ix_compliance_runs_started_at'), table_name='compliance_runs')
    op.drop_table('compliance_runs')
    op.drop_index('ix_command_logs_user_ts', table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_tenant_id'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_session_id'), table_name='command_logs')
    op.drop_index('ix_command_logs_device_ts', table_name='command_logs')
    op.drop_table('command_logs')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_target', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_ts', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_event_type'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_channels_tenant_id'), table_name='alert_channels')
    op.drop_table('alert_channels')
    op.drop_table('vendors')
    op.drop_table('tenants')
    op.drop_table('permissions')
    # ### end Alembic commands ###
